config/routes.rb
Rails.application.routes.draw do
  get 'map/index/:id' => 'map#index', as: 'map'
  post 'like/:note_id' => 'likes#like', as: 'like'
  delete 'unlike/:note_id' => 'likes#unlike', as: 'unlike'

  devise_for :users
  root 'home#top'
  resources :users, only:[:index, :show, :edit, :update] do
    member do
      get :like_notes
    end
  end
    
  resources :notes do
    collection do
      get 'search'
    end
    resources :comments, only: [:create]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :note
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :image, presence: true
  validates :content, length: {maximum: 140}
  validates :user_id, presence: true

  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy


  geocoded_by :address
  after_validation :geocode

  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :notes
  has_many :comments
  has_many :likes
  has_many :like_notes, through: :likes, source: :note

  # geocoded_by :address
  # after_validation :geocode

  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include ApplicationHelper
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :prefecture_name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(content: params[:content], note_id: params[:note_id], user_id: current_user.id)
    redirect_to note_path(@comment.note.id)
  end

  private
  def comment_params
    params.permit(:content, :note_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def like
    @note = Note.find(params[:note_id])
    like = current_user.likes.build(note_id: @note.id)
    like.save
  end

  def unlike
    @note = Note.find(params[:note_id])
    like = current_user.likes.find_by(note_id: @note.id)
    like.destroy
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  # before_action :current, only:[:edit, :update, :destroy]


  def search
    @user = User.where('prefecture_name LIKE(?)', "%#{params[:keyword]}%").first
    @users = User.where('prefecture_name LIKE(?)', "%#{params[:keyword]}%")
    @search_answers = []
    @users.each do |user|
      @search_answers += user.notes
    end
    
    gmaps_markers(@search_answers)
    # @search_answers = @search_answers.order("created_at DESC")
  end

  def index
    @notes = Note.all
    @title = "投稿一覧"
  end

  def show
    @comments = @note.comments.includes(:user)
    if @note.address
      gmaps_markers(@note)
    end
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    file = params[:note][:image]
    @note.set_image(file)
    if @note.save
      redirect_to @note, notice: "投稿が保存されました"
    else
      render :new
    end
  end

  def update
    file = params[:note][:image]
    @note.set_image(file)
    if @note.update(note_params)
      redirect_to @note, notice: "投稿が更新されました"
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to user_path(@note.user.id), notice: "投稿が削除されました"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :content, :address)
    end

    def current
      note = Note.find(params[:id])
      if !current_user?(note.user)
        redirect_to root_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :current, only:[:edit, :update]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    file = params[:user][:image]
    @user.set_image(file)
    if @user.update(user_params)
      redirect_to @user, notice: "ユーザー情報が更新されました"
    else
      render :edit
    end
  end

  def like_notes
    @notes = @user.like_notes
    @title = "いいね一覧"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end

    def current
      user = User.find(params[:id])
      if !current_user?(user)
        redirect_to notes_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    if !current_user.nil?
      current_user.id == user.id
    end
  end

  def gmaps_markers(hash)
    @hash = Gmaps4rails.build_markers(hash) do |h, marker|
      marker.lat h.latitude
      marker.lng h.longitude
      marker.infowindow h.title
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def image_for(user)
    if user.image
      image_tag "/user_images/#{user.image}", class: "user-image"
    else
      image_tag "雪猫.JPG", class: "user-image"
    end
  end
end

app/views/home/top.html.erb
  <div class="top-wrapper">
      <div class="bg-inner">
        <div class="top-text">
          <h1>生まれた街を紹介しよう</h1>
          <p>知られていない場所、気軽に楽しめる場所をシェアしてみよう</p>
       </div>
       <div class="searcher">
        <div class="bg-inner-2">
         <%= form_tag search_notes_path, method: :get do %>
            <input class="search__query" name="keyword" placeholder="都道府県で検索" type="string" value=""><button class="btn-search" title="検索" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button></input>
        <% end %>
        </div>
       </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Localstand</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyAESbtacSB87TovWTDM-pfqEeTj0H_bmUQ"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
</head>
<body>
<header>
  <div class="header-left">
    <%= link_to "SS", root_path, class: "left" %>
    <%= form_tag search_notes_path, method: :get, class: "left" do %>
    <i class="fa fa-search left" aria-hidden="true"></i><input class="search__query left" name="keyword" placeholder="都道府県で検索" type="string" value=""></input>
    <% end %>
  </div>
  <% if user_signed_in? %>
  <div class="header-right">
    <ul>
      <li><%= link_to "投稿する", new_note_path %></li>
      <li><%= link_to "投稿一覧", notes_path %></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to current_user.name, user_path(current_user.id) %></li>
    </ul>
  <% else %>
  <div class="header-right">
    <ul>
      <li><%= link_to "投稿一覧", notes_path %></li>
      <li><%= link_to "アカウント作成", new_user_registration_path %></li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
    </ul>
  </div>
  <% end %>
</header>

<%= yield %>

<footer>
  <small>-sightseeing--</small>
</footer>

</body>
</html>

app/views/likes/_like_links.html.erb
<% if current_user.likes.find_by(note_id: note.id) %>
  <%= link_to 'いいねを取り消す', unlike_path(note.id), method: :delete, remote: true %>
<% else %>
  <%= link_to 'いいね！', like_path(note.id), method: :post, remote: true %>
<% end %>

app/views/likes/like.js.erb
$('#like-link').html('<%= escape_javascript(render("likes/like_links", note: @note)) %>');
$('#like-count').html('<%= @note.likes.count %>人がいいね！と言っています');

app/views/likes/unlike.js.erb
$('#like-link').html('<%= escape_javascript(render("likes/like_links", note: @note)) %>');
$('#like-count').html('<%= @note.likes.count %>人がいいね！と言っています');

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @note.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-wrapper">
  <div class="container-2">
    <div class="new-form edit-form">
      <div class="field">
      <%= f.file_field :image, class: "form-box" %>
      </div>

      <div>
      <%= f.text_field :address, placeholder: "場所", class: "form-box" %>
      </div>

      <div class="field">
      <%= f.text_field :title, placeholder: "タイトル", class: "form-box" %>
      </div>

      <div class="field">
      <%= f.text_area :content, placeholder: "コメント", class: "form-box" %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit "保存" %>
    </div>
  </div>
</div>

<% end %>

app/views/notes/_note.html.erb
<div class="index-images">
  <%= link_to note_path(note.id) do %>
    <%= image_tag "/user_images/#{note.image}", class: "index-image" %>
    <p class="index-title"><%= note.title %></p>
  <% end %>
</div>

app/views/notes/edit.html.erb
<div class="top-bar">
  <div class="container-1">
    投稿を編集する
  </div>
</div>

<%= render 'form' %>

app/views/notes/index.html.erb
<div class="top-bar">
  <div class="container-1">
    投稿一覧
  </div>
</div>

<div class="container-2">
  <div class="images-box">
      <% @notes.each do |note| %>
        <div class="index-images">
          <%= link_to note_path(note.id) do %>
            <%= image_tag "/user_images/#{note.image}", class: "index-image" %>
            <p class="index-title"><%= note.title %></p>
          <% end %>
        </div>
      <% end %>
    <div class="clear"></div>
  </div>
</div>

app/views/notes/new.html.erb
<div class="top-bar">
  <div class="container-1">
    投稿する
  </div>
</div>

  <%= render 'form' %>

app/views/notes/search.html.erb
<div class="top-bar">
  <div class="container-1">
    <%=  @user.prefecture_name %>
  </div>
</div>

<div class="container-2">

  <% if !@search_answers.nil? %>
    <div style='width: 100%;'>
      <div id="map" style='width: 97%; height: 400px;'></div>
    </div>

    <script type="text/javascript">
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    </script>
  <% end %>

  <div class="images-box search-index">
      <% @search_answers.each do |note| %>
        <div class="index-images">
          <%= link_to note_path(note.id) do %>
            <%= image_tag "/user_images/#{note.image}", class: "index-image" %>
            <p class="index-title"><%= note.title %></p>
          <% end %>
        </div>
      <% end %>
    <div class="clear"></div>
  </div>
</div>

app/views/notes/show.html.erb
<div class="top-bar">
  <div class="container-1">
    <%= @note.title %>
  </div>
</div>
<p id="notice" class="notice"><%= notice %></p>

<div class="container-2">

<% if !@note.address.nil? %>
  <div style='width: 100%;'>
    <div id="map" style='width: 100%; height: 400px;'></div>
  </div>

  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  </script>
<% end %>

  <div class="note-show">
    <div class="each-image">
    <%= link_to user_path(@note.user.id) do %>
      <%= image_tag "/user_images/#{@note.image}", class: "big-image" %>
    <% end %>
    </div>
    <div class="each-content">
      <%= @note.content %>
    </div>
  </div>

  <% if current_user?(@note.user) %>
    <div class="btn-wrapper">
      <%= link_to '編集', edit_note_path(@note.id), class: "edit-mini" %>
      <%= link_to '削除', note_path(@note.id), class:"delete-mini", method: :delete %>
    </div>
  <% end %>

  <br>
  <div id="like-link">
    <%= render "likes/like_links", note: @note %>
  </div>
  <div id="like-count">
    <%= @note.likes.count %>人がいいね！と言っています
  </div>

  <% if user_signed_in? %>
    <%= form_tag note_comments_path(@note.id), method: 'post' do %>
      <textarea cols="30" name="content" placeholder="コメントする" rows="3" class="comment-box"></textarea>
      <br><input type="submit" value="投稿" class="submit-btn">
    <% end %>
  <% end %>

  <div class="comments">
    <h3><コメント一覧></h3>
    <% if !@comments.empty? %>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.name, user_path(comment.user_id) %>：</strong>
          <%= comment.content %>
        </p>
      <% end %>
    <% else %>
      <p>コメントはまだありません</p>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<div class="container-1">
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @note.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<div class="form-wrapper">
  <div class="container-2">
    <div class="edit-form">
      <div class="field">
        画像
        <%= f.file_field :image, class: "form-box" %>
      </div>

      <div class="field">
        名前
        <%= f.text_field :name, class: "form-box" %>
      </div>

      <div class="field">
        メールアドレス
        <%= f.text_field :email, class: "form-box" %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit "保存" %>
    </div>
  </div>
</div>

<% end %>

app/views/users/edit.html.erb
<div class="top-bar">
  <div class="container-1">
    プロフィール編集
  </div>
</div>

<%= render 'form' %>

app/views/users/like_notes.html.erb
<div class="top-bar">
  <div class="container-1">
    <%= @title %>
  </div>
</div>

<div class="container-2">
  <div class="images-box">
    <%= render @notes %>
    <div class="clear"></div>
  </div>
</div>

app/views/users/show.html.erb
<div class="top-bar">
  <div class="container-1">
    アカウント情報
  </div>
</div>
<p id="notice" class="notice"><%= notice %></p>


<div class="container-2">

  <div class="user-info" >
      <%= image_for(@user) %>

    <div class="name-mail" >
      <ul>
        <li><%= @user.name %></li>
        <li><%= @user.email %></li>
      </ul>
    </div>
    <% if current_user?(@user) %>
      <div class="edit">
        <%= link_to '編集', edit_user_path(@user.id), class: "edit-btn" %>
      </div>
    <% end %>

  <%= link_to @user.likes.count, like_notes_user_path(@user.id) %>件の投稿にいいね！しています
  
  </div>


  <div class="image-contents">
    <% @user.notes.each do |note| %>
      <%= link_to note do %>
        <%= image_tag "/user_images/#{note.image}", class: "images" %>
      <% end %>
    <% end %>
    <div class="images"></div>
    <div class="images"></div>
    <div class="images"></div>
    <div class="images"></div>
    <div class="images"></div>
    <div class="images"></div>
    <div class="images"></div>
  </div>
  <div class="clear"></div>

</div>